// <auto-generated />
using AdessoDraw.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdessoDraw.Domain.Migrations
{
    [DbContext(typeof(DrawContext))]
    partial class DrawContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdessoDraw.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Almanya"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fransa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hollanda"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Portekiz"
                        },
                        new
                        {
                            Id = 6,
                            Name = "İtalya"
                        },
                        new
                        {
                            Id = 7,
                            Name = "İspanya"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Belçika"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
